<?php

/**
 * @file
 * Contains gary_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\gary_custom\GaryFunctions;

/**
 * Implements hook_help().
 */
function gary_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_custom module.
    case 'help.page.gary_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Primary Module for Custom Gary Code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gary_custom_theme() {
  return [
    'gary_custom' => [
      'render element' => 'children',
    ],
  ];
}

function gary_custom_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {

  if ($entity->bundle() == 'opportunities') {

  }
}
function gary_custom_entity_delete(EntityInterface $entity) {
  $helper = new GaryFunctions;

  switch ($entity->bundle()){
    case 'opportunity_services':

      //update total amount on parent
      $helper->updateTotalAmount($entity);
    break;
  }

}
function gary_custom_entity_update(EntityInterface $entity) {
  $helper = new GaryFunctions;

  //remove any old revisions on parahraphs
  $helper->cleanParagraphs($entity);

  switch ($entity->bundle()){
    case 'opportunity_services':

      //update total amount on parent
      $helper->updateTotalAmount($entity);
    break;
  }
}

function gary_custom_entity_presave(EntityInterface $entity) {
  $helper = new GaryFunctions;

  //calculate fields on project_units
  switch ($entity->bundle()){
    case 'project_units':

      //calculate ach50 field if its there
      if ($entity->hasField('field_ach50')) {
        $new_value = $helper->calculateField($entity, 'field_ach50');
        $entity->set('field_ach50', $new_value);
      }

      //calculate ach50 field if its there
      if ($entity->hasField('field_volume')) {
        $new_value = $helper->calculateField($entity, 'field_volume');
        $entity->set('field_volume', $new_value);
      }

      //update last updated field if pg item has changed
      if ($helper->entityHasChanged($entity)) {
        if ($entity->hasField('field_last_updated')) {
          $dt = new DateTime;
          $date = $dt->format("Y-m-d");
          $entity->set('field_last_updated', $date);
        }
      }

    break;

    case 'opportunity_services':
    break;

    default:
    break;
  }

}

function gary_custom_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {


  //Opportunity Services Calculation
  if ($form_id == 'inline_pg_form_field_opportunity_services_ref') {
    $form['#attached']['library'][] = 'gary_custom/service_price';

    //js listeners in js/service-price
    $form['container']['field_opportunity_service']['widget']['#attributes']['class'][] = "calculate-price";
    $form['container']['field_quantity']['widget'][0]['value']['#attributes']['class'][] = "update-price";
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function gary_custom_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type)  {
  // dpm($entity_type->id());
  // if ($entity_type->id() === 'paragraph') {
  //   $fields = [];
  //
  //   // Add a field that shows the completeness of the user profile.
  //   // This is computed whenever the profile changes, and then saved
  //   // to the database.
  //   $fields['completeness'] = BaseFieldDefinition::create('float')
  //     ->setLabel(t('Complete profile'))
  //     ->setDescription(t('User profile complete percentage, such as 0.40, i.e, 40%'))
  //     ->setDisplayOptions('view', [
  //       'label' => 'above',
  //       'weight' => -5,
  //     ]);
  //   //
  //   // // Add a field that shows a link to the user's current company.
  //   $fields['current_company'] = BaseFieldDefinition::create('current_company_link')
  //     ->setName('current_company')
  //     ->setLabel(t('Current company'))
  //     ->setComputed(TRUE)
  //     ->setClass('\Drupal\mymodule\CurrentCompanyLinkItemList')
  //     ->setDisplayConfigurable('view', TRUE)
  //     ->setDisplayOptions('view', [
  //       'label' => 'hidden',
  //       'weight' => -5,
  //     ]);
  //     ksm($fields);
  //   return $fields;
  // }
}
