field.field_settings.entity_reverse_lookup:
  type: mapping
  label: 'Entity Reverse Lookup Settings'
  mapping:
    parent_bundle:
      type: string
      label: 'Parent Bundle'
    parent_field_name:
      type: string
      label: 'Parent Field Name'
    value:
      type: string
      label: 'Value'
