gary_fields.field.entity_reverse_lookup:
  type: mapping
  label: 'Entity Reverse Lookup Settings'
  mapping:
    parent_bundle_shared:
      type: integer
      label: 'Parent Bundle Shared'
    parent_bundle:
      type: string
      label: 'Parent Bundle'
    parent_field_name:
      type: string
      label: 'Parent Field Name'
