#!/bin/bash
set -e

ssh garyDeploy "
  set -e
  cd /var/www/gary
  git pull
  cd drupal
  composer install
  cd ..
  npm install
  ./drupal/vendor/bin/drush config:import -y
  ./drupal/vendor/bin/drush cr
"
