<?php

/**
 * @file
 * Contains gary_import_scripts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\comment\Entity\Comment;

/**
 * Implements hook_help().
 */
function gary_import_scripts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_import_scripts module.
    case 'help.page.gary_import_scripts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Gary Import Scripts') . '</p>';
      return $output;

    default:
  }
}

function attachServiceTasksToServices() {
  $nodes = serviceIds();
  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  foreach ($nodes as $node_id => $auto_task_ids) {
      $node = $node_storage->load($node_id);
      if ($node->bundle() == 'services') {
        if ($node->hasField('field_service_tasks')) {
          $current = $node->get('field_service_tasks')->getValue();
          $auto_task_array = explode(',',$auto_task_ids);
          foreach ($auto_task_array as $old_auto_task_id) {
            $new_auto_task_id = getAutoTaskId($old_auto_task_id);
            if (!empty($new_auto_task_id)) {
              $current[] = [
                'target_id' => $new_auto_task_id
              ];
            } else {
              $messenger = \Drupal::messenger();
              $messenger->addMessage('COULD NOT FIND NEW ID!'.$old_auto_task_id, $messenger::TYPE_WARNING);
            }
          }
          $node->set('field_service_tasks', $current);
          $node->save();
        } else {
          // dpm('no field');
        }
      } else {
        // dpm('no bundle');
      }
  }
  // $entity->set('field_service_tasks', 6796);
  // $entity->set('field_service_tasks', 6820);
  // $entity->save();
}

function gary_import_scripts_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // ksm(count(autoTaskIds()));
  if (isset($_GET['process']) == 1 && $entity->id()=='6551') {
    // $csv = array_map('str_getcsv', file('services_export_ready_friday_test.csv'));
    // // $node_storage = \Drupal::entityTypeManager()->getStorage('node');
    // dpm($csv[0]);
    // unset($csv[0]);
    // // return;
    // ksm($csv);
    $p = importOppServices();
  }
}

function importOppServices() {
  $csv = array_map('str_getcsv', file('services_export_new_ready.csv'));

  $new_array = [];
  $csv2 = $csv;
  unset($csv[0]);
  // ksm($csv2);
  foreach ($csv as $key => $value_array) {
    foreach ($value_array as $value_key => $value) {
      if ($value_key == 0) {
        if (isset($new_array[$value])) {
          $new_array[$value][] = [$csv2[$key]];
        } else {
          $new_array[$value] = [$csv2[$key]];
        }
        continue;
      }
    }

  }

  $node_storage = \Drupal::entityTypeManager()->getStorage('node');
  foreach ($new_array as $parent_id => $paragraphs) {
    $node = $node_storage->load($parent_id);
    // $current = $node->get('field_opportunity_services_ref')->getValue();
    $current = [];
    foreach ($paragraphs as $index => $paragraph_values) {
      $pg_item = Paragraph::create(['type' => 'opportunity_services',]);
      if(is_array($paragraph_values[0])) {
        $paragraph_values = $paragraph_values[0];
      }
      if(trim($paragraph_values[1]) != "") {
        $pg_item->set('field_opportunity_service', $paragraph_values[1]);
      }
      if(trim($paragraph_values[2]) != "") {
        $pg_item->set('field_service_amount', $paragraph_values[2]);
      }
      if(trim($paragraph_values[3]) != "") {
        $pg_item->set('field_quantity', $paragraph_values[3]);
      }
      if(trim($paragraph_values[4]) != "") {
        $pg_item->set('field_line_total', $paragraph_values[4]);
      }
      $pg_item->isNew();
      $pg_item->save();
      $current[] = array(
          'target_id' => $pg_item->id(),
          'target_revision_id' => $pg_item->getRevisionId(),
        );
    }


    $node->set('field_opportunity_services_ref', $current);
    $node->save();
  }
}

function deleteAllContentOfType() {
  // $result = \Drupal::entityQuery('node')
  //   ->condition('type', 'messages')
  //   ->execute();
  // entity_delete_multiple('node', $result);
  // $resultt = \Drupal::entityQuery('comment')
  //   ->execute();
  // entity_delete_multiple('comment', $resultt);
}

function importCsv() {
  foreach ($csv as $key => $value) {
      // $user = $user_object->loadByProperties(['name' => $value[1]]);
      // $x = reset($user);
      \Drupal::logger('commentstag')->debug($key);

      $comment_values = [
        'entity_type' => 'node',            // required.
        'entity_id'   => $value[2],                // required.
        'field_name'  => 'field_comments',         // required.
        'uid' => $value[1],                         // required.
        'comment_type' => 'comment',        // required.
        'subject' => $value[0],  // required.
        'comment_body' => $value[6],            // optional.
        'status' => 1,                      // optional. Defaults to 0.
        'created' => strtotime($value[7]),
        'changed' => strtotime($value[7]),
        'field_comment_audit_id' => $value[4],                      // optional. Defaults to 0.
        'pid' => $value[5],
      ];
      $comment = Comment::create($comment_values);
      $comment->save();
  }
}
