homebox.homebox.*:
  type: config_entity
  label: 'Homebox config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    path:
      type: string
      label: 'Path'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
    options:
      type: sequence
      label: 'Visibility'
      sequence:
        type: string
        label: 'Option'
    blocks:
      type: sequence
      label: 'Blocks'
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          title:
            type: string
          weight:
            type: integer
          region:
            type: string
          status:
            type: boolean
    columns:
      type: sequence
      label: 'Columns'
      sequence:
        type: string
        label: 'Columns'