<?php

/**
 * @file
 * Contains gary_dashboard.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function gary_dashboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_dashboard module.
    case 'help.page.gary_dashboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dashboard handler and display') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function gary_dashboard_theme() {
  return [
    'gary_dashboard' => [
      'variables' => [
        'region' => NULL,
        'adminsettings' => NULL
      ],
      'render element' => 'children',
    ],
    'dashboard_admin_form' => [
      'variables' => [
        'layout' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}

function gary_dashboard_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  //add popup form filters when we want to
  if ($route_name == 'gary_dashboard.dashboard') {
    $form['#attributes']['class'][] = 'hidden';
    $form['#attributes']['class'][] = 'popup-exposed-form';
  }
}
