<?php

/**
 * @file
 * Contains gary_custom_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Field\FieldStorageConfigInterface;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function gary_custom_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_custom_views module.
    case 'help.page.gary_custom_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom views, view fields, etc. for Gary') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_field_views_data_alter().
 *
 * Views integration for entity reference fields which reference nodes.
 * Adds a term relationship to the default field data.
 *
 * @see views_field_default_views_data()
 */
function gary_custom_views_field_views_data_alter(array &$data, FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() == 'entity_reference' && $field_storage->getSetting('target_type') == 'user') {
    foreach ($data as $table_name => $table_data) {
      foreach ($table_data as $field_name => $field_data) {
        if (isset($field_data['filter']) && $field_name != 'delta') {
          $data[$table_name][$field_name]['filter']['id'] = 'user_index';
        }
      }
    }
  }
  if ($field_storage->getType() == 'entity_reference' && $field_storage->getSetting('target_type') == 'node') {
    foreach ($data as $table_name => $table_data) {
      foreach ($table_data as $field_name => $field_data) {
        if (isset($field_data['filter']) && $field_name != 'delta') {
          $data[$table_name][$field_name]['filter']['id'] = 'node_index_nid';
        }
      }
    }
  }
}

/**
 * implements hook_views_query_alter()
 * For some reason I could not do this hook in the
 * gary_custom module. The first param passed in was wrong.
 * @param ViewExecutable $view
 * @param Sql $query
 */
function gary_custom_views_views_query_alter(ViewExecutable $view, Sql $query) {

  //when relating to a pargraph field we get duplicate results. Group by parent nid in this case
  if ($view->id() == 'reports_projects_by_service') {
    //lets leave if we dont have the paragraph relation
    if (! isset($view->relationship['field_opportunity_services_ref'])) {
      return;
    }

    $query->addField('node_field_data', 'nid', '', ['function' => 'groupby']);
    $query->addGroupBy('node_field_data.nid');

    foreach ($query->orderby as $filter) {
      $query->addGroupBy($filter['field']);
    }

  }
}
