<?php

/**
 * @file
 * Contains gary_email_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function gary_email_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_email_views module.
    case 'help.page.gary_email_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a header field and handler for emailing a particular view to a recipient') . '</p>';
      return $output;

    default:
  }
}

function gary_email_views_views_pre_render(ViewExecutable $view) {
  	if (isset($view->header['email_views'])) {
      // ksm($view->exposed_data);
      $options = $view->header['email_views']->options;

      if ($options['use_current_users_email'] == 1) {
        $user = '';
      }

      $def_recipient = $options['default_recipient'];
      $def_subject = $options['default_subject'];
      $def_body = $options['default_body'];
      // ksm($view->display_handler->handlers['header']);
      // ksm($view->current_display);

      // ksm($view->header['email_views']->render()['email_link']['#results']);

    }
}
