<?php

/**
 * @file
 * Contains gary_email_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function gary_email_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gary_email_views module.
    case 'help.page.gary_email_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a header field and handler for emailing a particular view to a recipient') . '</p>';
      return $output;

    default:
  }
}

/**
* Implements hook_mail().
*/
function gary_email_views_mail($key, &$message, $params) {

 $options = array(
   'langcode' => $message['langcode'],
 );

 if ($key == 'email_view') {
  //  ksm($params['email_from']);
   $from = !empty($params['email_from']) ? $params['email_from'] : \Drupal::config('system.site')->get('mail');
   $message['from'] = $from;
   $message['subject'] = t('@subject', ['@subject' => $params['email_subject']]);
   $message['body'][] = $params['body_msg'];
   $message['body'][] = $params['rendered_view'];
   $message['headers'] = [
    'content-type' => 'text/html',
    'MIME-Version' => '1.0',
    'reply-to' => $from,
    'Return-Path' => $from,
    'from' => 'Admin <'.$from.'>'
   ];

 }


}
