_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  date_popup: 0
  datetime: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gary_comments: 0
  gary_custom: 0
  gary_custom_views: 0
  gary_dashboard: 0
  gary_email_views: 0
  gary_field_formatter: 0
  gary_fields: 0
  gary_google_maps_api: 0
  gary_pdf_templates: 0
  geolocation: 0
  help: 0
  history: 0
  image: 0
  layout_discovery: 0
  link: 0
  media: 0
  menu_ui: 0
  multiple_fields_remove_button: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  rest: 0
  restui: 0
  search: 0
  search_autocomplete: 0
  select2: 0
  serialization: 0
  shortcut: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_xdebug: 0
  update: 0
  user: 0
  viewfield: 0
  views_autocomplete_filters: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_entity_form_field: 0
  views_field_formatter: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  gary: 0
profile: standard
