_core:
  default_config_hash: GbwamktrK8GXKxWeEk8m8o_PWXbPj2vOiFqIANDYIEc
langcode: en
id: search_form_content
uuid: d0010819-5e85-4471-ae99-2304cf62d348
label: 'Search Form (content tab)'
selector: ''
status: true
minChar: 3
autoSubmit: true
autoRedirect: true
maxSuggestions: 10
noResultLabel: 'No results found containing the word [search-phrase].'
noResultValue: '[search-phrase]'
noResultLink: ''
moreResultsLabel: 'View all results containg term [search-phrase].'
moreResultsValue: '[search-phrase]'
moreResultsLink: ''
source: 'autocompletion_callbacks_words::words_autocompletion_callback'
theme: basic-blue.css
editable: true
deletable: false
